hosp<-c('hdh','gth','abb','acb','zwa','dda','rth','raq','sss')
hosp<-c(hosp,'hdh','eth','nbb','gjb','qwa','daz','wth','rgg','fss')
ranks<-c(3,6,12,43,25,99,11,31,6,25,12,25,12,99)
ranks<-c(ranks,25)
ranks<-c(ranks,2)
ranks<-c(ranks,12)
ranks<-c(ranks,25)
states<-c("TX","UT","NM","NM","UT","CL","NM","WA","CL","NM","NM","CL","WA")
states<-c(states,"NM","TX","UT","NM","NM")
a<-cbind.data.frame(ranks,hosp,states)
a$hosp<-as.character(a$hosp)
lista<-a[order(a$states,a$ranks),]
lista<-split(lista,lista$states)
l2<-lapply(lista,function(e) {e[1,]})
unsplit(l2,as.factor(names(l2)))
