version: '3'
services:
    gateway:
        image: openmined/grid-gateway:latest
        build: .
        environment:
                - PORT=5000
                - SECRET_KEY=ineedtoputasecrethere
                - DATABASE_URL=sqlite:///databasegateway.db
        ports:
        - 5000:5000
    redis:
        image: redis:latest
        expose:
        - 6379
        ports:
        - 6379:6379
    bob:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://gateway:5000
                - ID=Bob
                - ADDRESS=http://bob:3000/
                - REDISCLOUD_URL=redis://redis:6379
                - PORT=3000
        depends_on:
                - "gateway"
                - "redis"
        ports:
        - 3000:3000
    alice:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://gateway:5000
                - ID=Alice
                - ADDRESS=http://alice:3001/
                - REDISCLOUD_URL=redis://redis:6379
                - PORT=3001
        depends_on:
                - "gateway"
                - "redis"
        ports:
        - 3001:3001
    bill:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://gateway:5000
                - ID=Bill
                - ADDRESS=http://bill:3002/
                - REDISCLOUD_URL=redis://redis:6379
                - PORT=3002
        depends_on:
                - "gateway"
                - "redis"
        ports:
        - 3002:3002
    james:
        image: openmined/grid-node:latest
        environment:
                - GRID_NETWORK_URL=http://gateway:5000
                - ID=James
                - ADDRESS=http://james:3003/
                - REDISCLOUD_URL=redis://redis:6379
                - PORT=3003
        depends_on:
                - "gateway"
                - "redis"
        ports:
        - 3003:3003
